---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.sgatewood.dev
  resources:
  - jobdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.sgatewood.dev
  resources:
  - jobdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - api.sgatewood.dev
  resources:
  - jobdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch/v1
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch/v1
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch/v1
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
